.github/workflows/package-build-and-publish.yml

Create PR with the latest update version for the _version.py
Addresses

ci: update package release workflow to update version file

---

README.md

ci: update README.md

---

github_rate_limits_exporter/cli.py

add command line option (--version, -V) to show program's version
Addresses

feat: show program's version

---

requirements.d/tests.txt
tests/conftest.py
tests/test_cli.py
tests/test_collector.py
tests/test_github.py
tests/test_utils.py
tests/utils.py

Add extra unit tests for the AccessToken class.
Reformat the unittests using black,isort
This issue is prerequisite before moving forward to the the access token refresh mechanism.
Addresses

GitHub access token extra tests

---

.github/workflows/app-linting-and-testing.yml
.github/workflows/chart-linting-and-testing.yml
.github/workflows/chart-package-and-publish.yml
.github/workflows/container-build-test-and-publish.yml
.github/workflows/package-build-and-publish.yml

update github action workflows, adapt github actions on the newest workflow
Addresses

ci: update github action workflows

---

requirements.d/bdist.txt
tox.ini

145 extra steps to the release workflow

---

charts/github-rate-limits-exporter/templates/_helpers.tpl
charts/github-rate-limits-exporter/templates/deployment.yaml
charts/github-rate-limits-exporter/unittests/deployment-test.yaml

- add checksum for secret and configmap for automatically upgrades through helm package manager
- update helm chart unittests
Addresses

chore(dev): update helm charts

---

Dockerfile
requirements.d/pylint.txt

chore(ci): update python slimit to 3.11.5
Addresses

chore(ci): update python slim to 3.11.5

---

Dockerfile

chore(ci): fix trivy  CVE-2023-5363

---

Dockerfile

fix: CVE-2023-47038 perl-base

---

requirements.d/bandit.txt
requirements.d/mypy.txt

chore(deps): constrain dependencies for python3.7

---

Dockerfile

chore(sec): update python to version 3.11.8

---

requirements.d/allure-tests.txt
requirements.d/tests.txt

build(deps): bump pytest from 7.4.4 to 8.0.2

---

charts/github-rate-limits-exporter/templates/tests/test-connection.yaml
kubernetes/prerequisites.sh

update k8s prerequisites.sh
minor fix in _helpers.tpl
add nodeSelector, helm delete policy hooks to test job
Addresses

chore(ci): Update exporter helm charts

---

Dockerfile

chore(docker): update to 3.11.9-slim

---

requirements.d/tests.txt
tox.ini

chore(dev): bump pytest-cov to v5.0.0

---

Dockerfile

chore(ci): fix CVE-2024-33599 libc

---

Dockerfile
requirements.d/dc.txt

chore(sec): fix setuptools CVE-2024-6345

---

Dockerfile
README.md
requirements.txt

chore: fix Dockerfile, upgrade cryptography==43.0.1

---

.github/workflows/app-linting-and-testing.yml
requirements.txt

chore(deps): restrict PyGithub version

---

Dockerfile
requirements.d/pylint.txt

change pylint requirements for 3.8 python version
change Dockerfile base image to 3.12.6-slim
Addresses

chore(ci): fix github action pipeline failures

---

.github/workflows/app-linting-and-testing.yml
.github/workflows/package-build-and-publish.yml
requirements.d/allure-tests.txt
requirements.d/bandit.txt
requirements.d/black.txt
requirements.d/isort.txt
requirements.d/mypy.txt
requirements.d/pylint.txt
requirements.d/tests.txt
requirements.txt
setup.py

chore(ci): deprecated python3.7

---

setup.py

chore(rel): update setup.py

---

requirements.d/tests.txt

chore(ci): add pytest-randomly version constrain

---

Dockerfile
requirements.d/tests.txt

chore(ci): pinned pytest-cov to 3.8 and >=3.9

---

.github/workflows/container-build-test-and-publish.yml

chore(dev): fix bandit, dockerize image step

---

docker-compose.yml
kubernetes/devbox.json
kubernetes/helmfile.lock
kubernetes/helmfile.yml
kubernetes/kind.yml
monitoring/grafana/datasources.yml
pytest.ini

chore(dev): update docker, kubernetes dependencies

---

.github/workflows/package-build-and-publish.yml
github_rate_limits_exporter/_version.py

chore(rel): update github workflow, version file

---

.github/workflows/chart-package-and-publish.yml
.github/workflows/package-build-and-publish.yml
github_rate_limits_exporter/_version.py

chore(rel): fix pull request action branches

---

github_rate_limits_exporter/__init__.py
github_rate_limits_exporter/__main__.py
github_rate_limits_exporter/_version.py
github_rate_limits_exporter/collector.py
github_rate_limits_exporter/constants.py
github_rate_limits_exporter/exceptions.py
github_rate_limits_exporter/github.py
github_rate_limits_exporter/utils.py
requirements.d/black.txt
requirements.d/isort.txt
requirements.d/mypy.txt
setup.py

chore(ci): Fix project dependencies

---

Dockerfile

chore(deps): update Dockerfile base image to 3.12.7-slim

---

requirements.txt
tests/conftest.py

chore(tests): fix test failures due to PyGithub update

---

.github/workflows/container-build-test-and-publish.yml
Dockerfile

chore(dev): update Dockerfile base python image

---

requirements.d/ipython.txt

chore(dev): set dependency markers for ipython

---

Dockerfile

chore(dev): update python to 3.12.11

---

.github/workflows/container-build-test-and-publish.yml

Update CI to build and push docker images for both amd64 and arm64 arch.
Allows to run on Graviton or equivalent compute instances.

feat(ci): arm64 docker image
